### ISSUE TITLE
[QC-0010] [ENHANCEMENT] Add amplifier bars to below the potions in the modpack

### ISSUE THREAD

**Issue by TechSupportRed** [Quartzmaven/Quartzs-Console-Issues#10]
Currently the modpack doesn't have the amplifier bar below

**This is what it should look like:**
![image](https://github.com/Quartzmaven/Quartzs-Console-Issues/assets/120854107/448d6ae1-5f5b-4505-bc96-9e119ada1677)

**Download this mod: https://www.curseforge.com/minecraft/mc-mods/distinguished-potions**
Edit the config and allow amplifier bars for this mod, and enable the glint cause this mod disables it for some reason, disable everything else in config except for enabling this setting.

**Comment by Quartzmaven** [comment]
Was planning on adding that but unfortunately, in the console edition, **it was removed in 1.13.**

**Comment by TechSupportRed** [comment]
Oh wow, I didn't know it was removed. That's my bad
