### ISSUE TITLE
[QC-0011] [BUG] Lines in every block that is out of distance, usually appears in the end when looking above everything.

### ISSUE THREAD

**Issue by TechSupportRed** [Quartzmaven/Quartzs-Console-Issues#11]
**Lines in every block that is out of distance:**
![image](https://github.com/Quartzmaven/Quartzs-Console-Issues/assets/120854107/6800f799-d77a-4c3b-ba51-8eb564cb494f)

**Comment by Quartzmaven** [comment]
Can you try disable mipmaps? I disabled mipmaps for the 1.20 update.

**Comment by Quartzmaven** [comment]
If you're on NVIDIA, check your NVIDIA settings.
https://www.youtube.com/watch?v=7CUNh89y0oM

**Comment by TechSupportRed** [comment]
Fixed

**Comment by Quartzmaven** [comment]
Workaround will be in the next version.
