### ISSUE TITLE
[QC-0012] [BUG] End sky is bugged and doesn't appear with the actual console edition end skybox, instead just bugged and doesn't appear with any dots or anything.

### ISSUE THREAD

**Issue by TechSupportRed** [Quartzmaven/Quartzs-Console-Issues#12]
**What the end sky currently looks like:**
![image](https://github.com/Quartzmaven/Quartzs-Console-Issues/assets/120854107/86619e17-6448-4262-8683-c34514e6c391)

**What it is supposed to look like:**
![image](https://github.com/Quartzmaven/Quartzs-Console-Issues/assets/120854107/9d379f06-a88c-4f56-8382-058a8fb8e49b)

**Comment by Quartzmaven** [comment]
It's a Sodium issue. Someone had the same issue.

**Comment by Quartzmaven** [comment]
https://github.com/CaffeineMC/sodium-fabric/issues/1051

**Comment by Quartzmaven** [comment]
https://github.com/CaffeineMC/sodium-fabric/pull/710
