### ISSUE TITLE
[QC-0008] [BUG] Weird in-game flickering when moving around or doing anything.

### ISSUE THREAD

**Issue by TechSupportRed** [Quartzmaven/Quartzs-Console-Issues#8]
**Video demonstrating issue:**
https://github.com/Quartzmaven/Quartzs-Console-Issues/assets/120854107/96dc8dcf-0833-4556-a1ba-b85c0f319959

Just a flickering issue in Minecraft

**Comment by Quartzmaven** [comment]
Is this a graphics bug? It appears that I don't have this problem in mine.

**Comment by Quartzmaven** [comment]
Workaround: Try disabling "Borderless Mining" on the console window.

**Comment by TechSupportRed** [comment]
Fixed

**Comment by Quartzmaven** [comment]
Workaround will be in the next version.
