### ISSUE TITLE
[QC-0009] [ENHANCEMENT] Make the boss bar more accurate to the console edition bar

### ISSUE THREAD

**Issue by TechSupportRed** [Quartzmaven/Quartzs-Console-Issues#9]
**What it currently looks like:**
![image](https://github.com/Quartzmaven/Quartzs-Console-Issues/assets/120854107/f3ccd7e5-c79a-4863-86c3-c288562ab90a)

**What it looks like in console edition:**
![image](https://github.com/Quartzmaven/Quartzs-Console-Issues/assets/120854107/a8c8395b-4e4a-4fd4-b253-b2ed10747e84)

Making it look like the old xbox 360 edition boss fight bar

**Comment by Quartzmaven** [comment]
It has been added in my newest modpack that should come out at any day... Quartz's Console repository will be archived, removing all the resources, after a final update will release.
![2024-01-25_18 25 14](https://github.com/Quartzmaven/Quartzs-Console-Issues/assets/81502335/6fa5f83d-00e6-4212-8470-7f35f5add216)
